services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - is-net

  app:
    image: isapp:lab8
    container_name: isapp
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ConnectionStrings__Mssql=Server=mssql;Database=AppDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
      - App__Version=${APP_VERSION}
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - is-net

volumes:
  mssql_data:

networks:
  is-net:
